### PR TITLE
Add support for multiple theme targets on a single server

### PR DESCRIPTION
**Pull request by colinbowern**
Adding support for single-server, multi-theme deployments per https://groups.google.com/forum/?hl=en#!topic/scroll-viewport-dev/6HO0vQGY0wc

### CODE REVIEW

**Comment by jensrutschmann** [comment]
Hi @mschmick and @colinbowern 

I'd be glad to merge this, but could you apply the same fallback logic to the ```scope``` field as well?
It might make sense to put the dev version of a theme in the dev space, and the prod version in the prod space - for example if you don't have global admin permissions.

Also it would be great if you could adapt the README.md file accordingly.

Thanks!

**Comment by colinbowern** [comment]
@jensrutschmann Done

**Comment by colinbowern** [comment]
@jensrutschmann Done, please see the appended commits.

**Comment by mschmick** [comment]
Hi Jens,

In my time to read this, it seems you’ve patched already including for scope (cool). Is there anything else you need from me? Still want a README patch?

Thanks,
Mark

**Comment by colinbowern** [comment]
@jensrutschmann anything else I need to do to merge this PR?

**Comment by jensrutschmann** [comment]
@colinbowern thanks for your work, I'll merge this now.
@mschmick I don't think there's anything required from your side. I simply added you to this PR to keep you in the loop.

**Pull request merged**
